Repository CollaBu/pennyway-was, pull requests merged in 2024-04, with the labels that each got.

#31 ✨ 닉네임 중복검사 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/repository/UserRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
Labels: enhancement

#32 ✨ OIDC 기능 인터페이스화 (+ component scan에 대한 고찰)
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/OauthOidcHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/InfraConfig.java
  pennyway-common/src/main/java/kr/co/pennyway/common/util/MapUtils.java
  pennyway-infra/build.gradle
  pennyway-infra/src/main/java/kr/co/pennyway/PennywayInfraApplication.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/PennywayInfraApplication.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/apple/oidc/AppleOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/google/oidc/GoogleOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/kakao/oidc/KakaoOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/EnablePennywayInfraConfig.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/PennywayInfraConfig.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/PennywayInfraConfigGroup.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/PennywayInfraConfigImportSelector.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcClientProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProvider.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OidcDecodePayload.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OidcPublicKey.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OidcPublicKeyResponse.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/AppleOidcProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/GoogleOidcProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/KakaoOidcProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/CacheConfig.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/ConfigurationPropertiesConfig.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/DefaultFeignConfig.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/FeignConfig.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#33 ✨ OAuth OIDC 회원가입 및 로그인 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/OauthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignInReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/OauthOidcHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserOauthSignMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/converter/ProviderConverter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/exception/PhoneVerificationErrorCode.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapperTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/ProviderConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/phone/PhoneVerificationType.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthException.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/type/Provider.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
  pennyway-infra/build.gradle
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/apple/oidc/AppleOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/google/oidc/GoogleOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/kakao/oidc/KakaoOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcClient.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/CacheConfig.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#34 ✨ External-api 모듈 통합 테스트 환경 구축
  .github/workflows/test.yml
  pennyway-app-external-api/build.gradle
  pennyway-app-external-api/src/main/resources/application.yml
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiDBTestConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiIntegrationProfileResolver.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiIntegrationTestConfig.java
  pennyway-app-external-api/src/test/resources/application.yml
  pennyway-app-external-api/src/test/resources/logback-test.xml
  pennyway-common/src/main/java/kr/co/pennyway/common/PennywayCommonApplication.java
  pennyway-common/src/main/resources/application-common.yml
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-domain/src/test/resources/application-domain.yml
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#35 🐛 OIDC signature 검증없이 header, payload 추출 로직 수정
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
Labels: bug

#37 ✨ 인증코드 SMS 전송
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/PhoneVerificationMapper.java
  pennyway-infra/build.gradle
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/sms/AwsSmsProvider.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/sms/SmsDto.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/sms/SmsProvider.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/PushCodeEvent.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/PushCodeEventHandling.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/AwsSnsConfig.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#39 📝 Swagger 예외 응답 문서 개선
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/ErrorResponse.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/swagger/CustomJsonView.java
Labels: documentation

#40 🐛 Google id token issuer mismatch 이슈 해결
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/OauthOidcHelper.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcClientProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/AppleOidcProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/GoogleOidcProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/KakaoOidcProperties.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: bug

#44 ✏️ User name 필드 유효성 검사 기준 변경
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
Labels: enhancement

#43 ✨ User, Oauth Entity Soft Delete 반영
  pennyway-domain/build.gradle
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/config/ContainerMySqlTestConfig.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserSoftDeleteTest.java
  pennyway-domain/src/test/resources/logback-test.xml
Labels: enhancement

#45 ✏️ OAuth 계정 연동 실패 해결 및 테스트 케이스 추가
  pennyway-app-external-api/build.gradle
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserOauthSignMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/resources/payload/oidc-response.json
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-infra/src/main/resources/application-infra.yml
Labels: bug, enhancement

#46 ✏️ 인증번호 전송 api 통합
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/SmsApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/SmsController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/converter/VerificationTypeConverter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/exception/PhoneVerificationErrorCode.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/query/VerificationType.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
Labels: enhancement, discussion

#47 📝 모듈 별 README.md 추가
  .gitignore
  pennyway-app-external-api/README.md
  pennyway-common/README.md
  pennyway-domain/README.md
  pennyway-infra/README.md
Labels: documentation

#49 ✨ 로그아웃 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtAuthenticationFilter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/util/CookieUtil.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAuthControllerIntegrationTest.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/ReasonCode.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/exception/JwtErrorCode.java
Labels: enhancement

#52 🐛 OAuth Provider 필드 Conveter 누락 수정
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
Labels: bug

#36 ✨ 문의하기 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/api/QuestionApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/controller/QuestionController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/dto/QuestionReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/usecase/QuestionUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/question/controller/QuestionControllerTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/QuestionCategoryConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/QuestionCategory.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/exception/QuestionErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/exception/QuestionErrorException.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/repository/QuestionRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/service/QuestionService.java
  pennyway-infra/build.gradle
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/google/mail/GoogleMailSender.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/MailEvent.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/MailEventHandling.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MailConfig.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#53 🔧 인증 기능 리팩토링
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/SmsController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/UserSyncDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserOauthSignMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/PhoneVerificationService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserGeneralSignService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/SmsUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/query/VerificationType.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/UserGeneralSignMapperTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapperTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/service/UserGeneralSignServiceTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/phone/PhoneCodeKeyType.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/phone/PhoneCodeRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/phone/PhoneCodeService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/phone/PhoneValidationDaoTest.java
Labels: refactoring

#55 ✨ 사용자 본인 프로필 조회 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/type/ProfileVisibility.java
Labels: enhancement

#56 ✨ 로그인 상태 확인 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/UserAuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/AuthStateDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtAuthenticationFilter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/access/AccessTokenClaimKeys.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/refresh/RefreshTokenClaimKeys.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/WebSecurityUrls.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCaseUnitTest.java
Labels: enhancement

#48 일반 회원 아이디 찾기 API 구현
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthCheckApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/AuthFindDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/AuthFindService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/AuthFindMapperTest.java
Labels: enhancement

#59 ✨ 사용자 아이디/이름 수정 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/Device.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
Labels: enhancement

#60 ✨ 사용자 알림 설정 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/converter/NotifyTypeConverter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/NotifySetting.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
Labels: enhancement

#61 🐛 아이디 찾기 API 요청 시 휴대폰 번호 및 인증 코드를 입력하지 않을 경우 INTERNAL_SERVER_ERROR 해결
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthCheckApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/PhoneVerificationService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java
Labels: bug

#62 ✨ 비밀번호 검증/변경 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/helper/PasswordEncoderHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/UserFixture.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/ReasonCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
Labels: enhancement

#64 ✨ External Api Controller 로깅을 위한 AOP 구현
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/aop/ExternalApiLogAspect.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/aop/RequestHeaderLog.java
Labels: enhancement

#67 ✨ 인증된 사용자의 소셜 계정 연동 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/UserAuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/UserSyncDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserGeneralSignService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCaseUnitTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
Labels: enhancement
