Repository CollaBu/pennyway-was, pull requests merged in 2024-05, with the labels that each got.

#69 🐛 OAuth 로그인/회원가입 시 Soft Delete 정책 반영 검사
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/OauthOidcHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProvider.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
Labels: bug

#70 ✨ 인증된 사용자의 OAuth 연동 해지 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/UserAuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCaseUnitTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
Labels: enhancement

#72 ✏️ 마이 프로필 조회 시, 소셜 계정 연동 정보 추가
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/OauthAccountDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/mapper/UserProfileMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
Labels: enhancement

#73 ✨ 사용자 계정 삭제 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserDeleteService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/repository/UserRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
Labels: enhancement

#74 ✨ 지출 관리 영역 Domain 정의
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/SpendingIconConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/SpendingCustomCategory.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomCategoryRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/type/SpendingCategory.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/domain/TargetAmount.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java
Labels: enhancement

#75 🐛 사용자 삭제 시나리오 개선
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/Device.java
Labels: bug

#76 ✨ QueryDsl 확장 Repository 및 Util 정의
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/ExtendedRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/ExtendedRepositoryFactory.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryDslSearchRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryDslSearchRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryHandler.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/util/QueryDslUtil.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/util/SliceUtil.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/config/JpaConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/repository/UserRepository.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserExtendedRepositoryTest.java
Labels: enhancement

#77 ✨ 당월 목표 금액 설정 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountSaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountIntegrationTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/domain/TargetAmount.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/exception/TargetAmountErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/exception/TargetAmountErrorException.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java
Labels: enhancement

#78 ✨ 월별 사용자 지출 내역 조회 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingUseCaseIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
  pennyway-domain/build.gradle
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: enhancement

#81 ✨ 지출 내역 등록 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingCategoryManager.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingUseCaseIntegrationTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/dto/CategoryInfo.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/exception/SpendingErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomCategoryRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java
Labels: enhancement

#82 ✨ 사용자 정의 지출 카테고리 조회 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/SpendingCategoryConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/SpendingCustomCategory.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomCategoryRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java
Labels: enhancement

#84 ✏️ QueryDsl 확장 Repository의 Dto 불변성 보장을 위한 분기 처리
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryDslSearchRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryDslSearchRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryHandler.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserExtendedRepositoryTest.java
Labels: refactoring

#87 📝 Spring Docs Swagger UI 수정 및 API 그룹 매핑
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/SwaggerConfig.java
Labels: documentation

#85 🐛 사용자 계정 삭제 후 동일한 OAuth 회원가입 이후 로그인 에러 해결
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepositoryTest.java
Labels: bug

#86 ✏️ 테스트 작성 시 `@AuthenticatePrincipal` 어노테이션 대응
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtAuthenticationFilter.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/AuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/UserAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
Labels: refactoring

#88 ✨ 사용자 년/월 별 지출 총합 및 목표 금액 조회 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/TargetAmountFixture.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/UserFixture.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/dto/TotalSpendingAmount.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/domain/TargetAmount.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-domain/src/test/java/kr/co/pennyway/domain/config/TestJpaConfig.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepositoryTest.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserExtendedRepositoryTest.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserSoftDeleteTest.java
Labels: enhancement

#90 ✨ 당월 목표 금액 삭제 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/exception/TargetAmountErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java
Labels: enhancement

#92 🐛 지출 내역 조회 응답 및 스웨거 버그 픽스
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java
Labels: bug

#94 ✨ Firebase Cloud Messaging 기본 설정
  .github/workflows/deploy.yml
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/InfraConfig.java
  pennyway-infra/.gitignore
  pennyway-infra/build.gradle
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/PennywayInfraConfigGroup.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/FcmConfig.java
  pennyway-infra/src/main/resources/application-infra.yml
  pennyway-infra/src/main/resources/firebase/.gitkeep
Labels: enhancement

#95 ✨ 사용자 로그인 로그를 위한 Interceptor 및 환경 구축
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/interceptor/SignEventLogInterceptor.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/JwtClaimsParserUtil.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/question/controller/QuestionControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/IpAddressHeaderConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLog.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLogRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLogService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/domain/SignInLog.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/domain/SignInLogId.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/repository/SignInLogRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/service/SignInLogService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/type/IpAddressHeader.java
Labels: enhancement

#97 ✨ S3 정적 파일 업로드를 위한 Presigned-URL 발급 API 구현
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/api/StorageApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/controller/StorageController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/dto/PresignedUrlDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/usecase/StorageUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/storage/controller/StorageControllerTest.java
  pennyway-common/src/main/java/kr/co/pennyway/common/util/UUIDUtil.java
  pennyway-infra/build.gradle
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/AwsS3Provider.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ChatProfileUrlGenerator.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ChatUrlGenerator.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ChatroomProfileUrlGenerator.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/FeedUrlGenerator.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ObjectKeyTemplate.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ObjectKeyType.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ProfileUrlGenerator.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/UrlGenerator.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/UrlGeneratorFactory.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/exception/StorageErrorCode.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/exception/StorageException.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/AwsS3Config.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#96 ✨ 지출 내역 삭제 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: enhancement

#93 ✨ 지출 내역 수정 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateServiceTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java
Labels: enhancement

#99 Batch: ✨ Batch 기초 세팅 및 CD 파이프라인 수정 (수정될 PR 컨벤션 관련 내용 포함)
  .github/workflows/create-tag-and-release.yml
  .github/workflows/deploy-batch.yml
  .github/workflows/deploy-external-api.yml
  Dockerfile
  commitlint.config.js
  pennyway-app-external-api/Dockerfile
  pennyway-batch/.gitignore
  pennyway-batch/Dockerfile
  pennyway-batch/build.gradle
  pennyway-batch/src/main/java/kr/co/pennyway/PennywayBatchApplication.java
  pennyway-batch/src/main/resources/application.yml
  settings.gradle
Labels: enhancement

#100 Api: 🎇 Api-v1.0.0 릴리즈
  .github/workflows/create-tag-and-release.yml
Labels: enhancement
