Repository CollaBu/pennyway-was, pull requests merged in 2024-07, with the labels that each got.

#120 Api: ✨ 카테고리에 등록된 소비 리스트 무한 스크롤 조회 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/converter/SpendingCategoryTypeConverter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/query/SpendingCategoryType.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingCategoryManager.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/GetSpendingsByCategoryControllerTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/exception/SpendingErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/type/SpendingCategory.java
Labels: enhancement

#121 Api: ✨ 사용자 정의 카테고리 수정 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingCategoryDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingCategorySaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingCategoryManager.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryUpdateControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingCategoryUpdateIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingCustomCategoryFixture.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/SpendingCustomCategory.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/exception/SpendingErrorCode.java
Labels: enhancement

#122 Api: 🐛 N+1 문제 개선 테스트의 간헐적 실패문제 수정
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingCustomCategoryFixture.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
Labels: bug

#119 Api: ✨ 소비내역 복수 삭제 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingIdsDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingDeleteService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: enhancement

#123 Api: ✨ 사용자 정의 카테고리 삭제 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingCategoryDeleteService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingCategoryIntegrationTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: enhancement

#124 Batch: ✨ 정기 지출 등록 알림 배치 & 스케줄러
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiDBTestConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/PennywayBatchApplication.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/config/BatchConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/config/InfraConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/dto/DailySpendingNotification.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/job/DailySpendingNotifyJobConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/processor/NotificationProcessor.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/reader/ActiveDeviceTokenReader.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/scheduler/SpendingNotifyScheduler.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/step/SendSpendingNotifyStepConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/writer/NotificationWriter.java
  pennyway-batch/src/main/resources/application.yml
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/AnnouncementConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/NoticeTypeConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/dto/DeviceTokenOwner.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/domain/Notification.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/type/Announcement.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/type/NoticeType.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/config/ContainerDBTestConfig.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/config/ContainerMySqlTestConfig.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/device/repository/ActivatedDeviceSearchTest.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/notification/repository/SaveDailySpendingAnnounceInBulkTest.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/google/fcm/FcmManager.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/FcmNotificationEventHandler.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/NotificationEvent.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/NotificationEventHandler.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/AsyncConfig.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/FcmConfig.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MailConfig.java
Labels: enhancement

#126 🐛 OIDC key caching ttl fix
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/CacheConfig.java
Labels: fix

#127 Api: ✏️ 사용자 아이디, 전화번호 수정 API 분리
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/service/PhoneUpdateServiceTest.java
Labels: fix

#130 Ignore: ✨ Open API 코드 리뷰 CI 파이프라인 추가
  .github/workflows/create-tag-and-release.yml
  .github/workflows/open-api-code-review.yml
Labels: enhancement

#132 Api: 🐛 목표 금액 DELETE 유즈 케이스 잘못된 필터링 제거
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountDeleteService.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java
Labels: bug, fix

#133 Api: ✏️ 총 지출 총합 값의 정수 범위 초과 케이스를 고려하여 타입 수정
  .github/workflows/open-api-code-review.yml
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountSaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/dto/TotalSpendingAmount.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: fix

#136 Api: ✨ 미확인 푸시 알림 읽음 처리 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/api/NotificationApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/controller/NotificationController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/dto/NotificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/service/NotificationSaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/usecase/NotificationUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/NotificationManager.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/service/NotificationService.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/notification/repository/NotificationRepositoryUnitTest.java
Labels: enhancement

#137 Batch: ✏️ 매일 정기 푸시 알림 배치 성능 개선
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/dto/DailySpendingNotification.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/dto/DeviceTokenOwner.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/QuerydslNoOffsetPagingItemReader.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/QuerydslPagingItemReader.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/expression/Expression.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/expression/OrderExpression.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/expression/WhereExpression.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/expression/WhereNumberFunction.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/expression/WhereStringFunction.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/options/QuerydslNoOffsetNumberOptions.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/options/QuerydslNoOffsetOptions.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/options/QuerydslNoOffsetStringOptions.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/job/DailySpendingNotifyConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/job/DailySpendingNotifyJobConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/processor/.gitkeep
  pennyway-batch/src/main/java/kr/co/pennyway/batch/processor/NotificationProcessor.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/reader/ActiveDeviceTokenReader.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/step/SendSpendingNotifyStepConfig.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/writer/NotificationWriter.java
  pennyway-batch/src/main/resources/application.yml
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationCustomRepositoryImpl.java
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redisson/CouponDecreaseLockTest.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/device/repository/ActivatedDeviceSearchTest.java
Labels: refactoring

#138 Api: 🐛 Sms type 변환 시, 휴먼 에러 제거 및 예방
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/SmsApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/query/VerificationType.java
Labels: fix

#139 Api: ✨ 미확인 푸시 알림 존재 여부 확인 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/api/NotificationApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/controller/NotificationController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/service/NotificationSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/usecase/NotificationUseCase.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/service/NotificationService.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/notification/repository/NotificationRepositoryUnitTest.java
Labels: enhancement

#140 Batch: 🐛 정기 푸시 알림 배치 쿼리 픽스 & ItemReader 기능 수정
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/dto/DeviceTokenOwner.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/QuerydslNoOffsetPagingItemReader.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/QuerydslNoOffsetPagingItemReaderBuilder.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/options/QuerydslNoOffsetStringOptions.java
  pennyway-batch/src/main/java/kr/co/pennyway/batch/reader/ActiveDeviceTokenReader.java
Labels: bug, fix

#142 Api: 🐛 Spending Custom Category Delete Query Fix
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiDBTestConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/SpendingCustomCategory.java
Labels: bug, fix

#125 Api: ✨ 사용자 정의 카테고리 이동 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/query/SpendingCategoryType.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingCategoryIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateServiceTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: enhancement
