Repository CollaBu/pennyway-was, pull requests merged in 2024-03, with the labels that each got.

#1 ✨ 초기 프로젝트 설정
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pennyway-app-external-api/.gitignore
  pennyway-app-external-api/build.gradle
  pennyway-app-external-api/src/main/java/kr/co/pennyway/PennywayExternalApiApplication.java
  pennyway-app-external-api/src/main/resources/application.yml
  pennyway-app-external-api/src/test/resources/application.yml
  pennyway-common/.gitignore
  pennyway-common/build.gradle
  pennyway-common/src/main/java/kr/co/pennyway/common/annotation/Adapter.java
  pennyway-common/src/main/java/kr/co/pennyway/common/annotation/DomainService.java
  pennyway-common/src/main/java/kr/co/pennyway/common/annotation/Helper.java
  pennyway-common/src/main/java/kr/co/pennyway/common/annotation/Mapper.java
  pennyway-common/src/main/java/kr/co/pennyway/common/annotation/UseCase.java
  pennyway-common/src/main/resources/application-common.yml
  pennyway-domain/.gitignore
  pennyway-domain/build.gradle
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-infra/.gitignore
  pennyway-infra/build.gradle
  pennyway-infra/src/test/resources/application-infra.yml
  settings.gradle
Labels: enhancement

#3 📝 PULL_REQUEST_TEMPLATE.md 작성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 📝 에러 코드 공통화 및 인터페이스 작성
  pennyway-app-external-api/build.gradle
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/BaseErrorCode.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/CausedBy.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/DomainCode.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/FieldCode.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/GlobalErrorException.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/ReasonCode.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/StatusCode.java
  pennyway-common/src/test/java/kr/co/pennyway/common/exception/CausedByTest.java
Labels: enhancement

#7 ✨ JDBC & JPA & QueryDsl Configuration 설정
  pennyway-app-external-api/src/main/resources/application.yml
  pennyway-domain/.gitignore
  pennyway-domain/build.gradle
  pennyway-domain/src/main/java/kr/co/pennyway/DomainPackageLocation.java
  pennyway-domain/src/main/java/kr/co/pennyway/config/JpaConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/config/QueryDslConfig.java
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#8 Conventional Commit을 위한 Git Hooks 설정
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#10 ✨ OpenAPI Swagger config 설정
  pennyway-app-external-api/build.gradle
  pennyway-app-external-api/src/main/java/kr/co/pennyway/config/SwaggerConfig.java
  pennyway-app-external-api/src/main/resources/application.yml
  pennyway-common/src/main/resources/application-common.yml
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#12 Swagger 관련 환경 변수 오타 수정
  pennyway-app-external-api/src/main/resources/application.yml
Labels: bug

#14 ✨ 응답 공통화 및 전역 예외 처리
  pennyway-app-external-api/.gitignore
  pennyway-app-external-api/src/main/java/kr/co/pennyway/common/response/ErrorResponse.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/common/response/SuccessResponse.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/common/response/handler/GlobalExceptionHandler.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/common/response/SuccessResponseTest.java
  pennyway-common/src/main/java/kr/co/pennyway/common/exception/ReasonCode.java
Labels: enhancement

#16 ✨️ 회원가입 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/JwtAuthMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/Jwts.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/refresh/RefreshTokenProvider.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/util/CookieUtil.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotEmoji.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotEmojiValidator.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotWhiteSpace.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotWhiteSpaceValidator.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/Password.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/PasswordValidator.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/response/SuccessResponseTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/security/jwt/access/AccessTokenProviderTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshToken.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenServiceImpl.java
Labels: enhancement

#17 Dockfile 작성
  .gitignore
  Dockerfile
Labels: enhancement

#19 CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  gradlew
Labels: enhancement

#21 CD Workflow 수정
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  build.gradle
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelper.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelperTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/response/SuccessResponseTest.java
  pennyway-infra/src/main/java/kr/co/pennyway/PennywayInfraApplication.java
Labels: bug

#22 ✨ Spring Security 초기 설정 (+ Test case 에러 관련)
  pennyway-app-external-api/build.gradle
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/UserDetailServiceImpl.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/MethodSecurityConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelperTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/response/SuccessResponseTest.java
  pennyway-domain/src/main/resources/application-domain.yml
Labels: bug, enhancement

#23 ✨ 로그인 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignInReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelperTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/repository/UserRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
Labels: enhancement

#24 ✏️ 회원가입 API 개선 (+ Domain Service Runtime 예외 발생 제거)
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserGeneralSignMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/UserDetailServiceImpl.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/helper/UserSyncHelperTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/UserGeneralSignMapperTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapperTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
Labels: enhancement

#25 ✨ Jwt 인증 필터
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/annotation/RefreshTokenStrategy.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtAuthenticationFilter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtExceptionFilter.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/handler/JwtAccessDeniedHandler.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/handler/JwtAuthenticationEntryPoint.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/JwtSecurityConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityFilterConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/forbidden/ForbiddenToken.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/forbidden/ForbiddenTokenRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/forbidden/ForbiddenTokenService.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/exception/JwtErrorCode.java
Labels: enhancement

#26 📑 Readme v0.0.2
  README.md
Labels: documentation

#30 ✏️ Swagger + Security 수정
  .github/workflows/deploy.yml
  pennyway-app-external-api/build.gradle
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignInReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/CustomGrantedAuthority.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/JacksonConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/SwaggerConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/CorsConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityAdapterConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityAuthConfig.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
  pennyway-app-external-api/src/main/resources/application.yml
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/ServerProperties.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/ConfigurationPropertiesConfig.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: bug
