Repository CollaBu/pennyway-was, pull requests merged in 2024-08, with the labels that each got.

#143 Api: ✏️ 사용자 삭제 로직 추가
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserDeleteService.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserDeleteServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/TestJpaConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/service/DeviceTokenService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomCategoryRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: fix

#144 Batch: 🐛 Batch 애플리케이션 timezone 수정
  pennyway-batch/src/main/java/kr/co/pennyway/PennywayBatchApplication.java
Labels: bug, fix

#145 Ignore: ✨ 프로필 사진 삭제 API 및 수정 API 픽스, 리팩토링
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/api/StorageApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/controller/StorageController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/dto/PresignedUrlDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/usecase/StorageUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/mapper/UserProfileMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/storage/AwsS3Adapter.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/storage/controller/StorageControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/AwsS3Provider.java
Labels: enhancement, refactoring

#146 Ignore: ✨ 애플리케이션 헬스 체크를 위한 Actuator 의존성 추가
  pennyway-app-external-api/build.gradle
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
Labels: enhancement

#147 Api: ✏️ HttpRequestMethodNotSupportedException 전역 예외 설정
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java
Labels: fix

#148 Ignore: 🐛 Devcie Token 삭제 시, 사용자가 정보 삭제되는 에러 핸들링
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/DeviceTokenUnregisterService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/DeviceToken.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
Labels: bug, fix

#149 Ignore: 🐛 Missing Request Cookie Header 예외 핸들러 추가
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java
Labels: bug, fix

#150 Ignore: 🔧 Swagger 에러 정의 어노테이션
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/annotation/ApiExceptionExplanation.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/annotation/ApiResponseExplanations.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/swagger/ApiExceptionExplainParser.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/SwaggerConfig.java
Labels: refactoring

#151 Ignore: 🔧 Redisson Auto Configuration 제거 및 도메인 모듈 의존 제어
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/DomainConfig.java
  pennyway-batch/src/main/resources/application.yml
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/aop/CallTransactionFactory.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/aop/DistributedLockAspect.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/aop/RedissonCallNewTransaction.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/aop/RedissonCallSameTransaction.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/importer/EnablePennywayDomainConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/importer/PennywayDomainConfig.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/importer/PennywayDomainConfigGroup.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/importer/PennywayDomainConfigImportSelector.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/config/RedissonConfig.java
  pennyway-domain/src/main/resources/application-domain.yml
  pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redisson/CouponDecreaseLockTest.java
Labels: refactoring

#152 Api: ✏️ Device Token Session 관리를 위한 로직 수정
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/DeviceTokenRegisterService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/DeviceTokenUnregisterService.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/DeviceTokenRegisterServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/DeviceTokenUnregisterServiceTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/DeviceToken.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/exception/DeviceTokenErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/service/DeviceTokenService.java
Labels: fix

#153 Batch: ✏️ 공지 푸시 알림 Reader에서 Device Token 조회 조건 추가
  pennyway-batch/src/main/java/kr/co/pennyway/batch/reader/ActiveDeviceTokenReader.java
Labels: fix

#155 Ignore: 🐛 교통 아이콘 상수 이름 수정
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/type/SpendingCategory.java
Labels: fix

#156 Api: ✏️ OAuth 계정 연동 누락된 예외처리 수정 (OAuth 연동 정책 수정)
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/UserSyncDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserGeneralSignService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/UserAuthControllerIntegrationTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
Labels: fix

#157 Api: 🐛 카테고리 별 소비 내역 리스트 조회 정렬 조건 수정
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java
Labels: bug, fix

#154 🔧 Blue-Green 배포를 위한 deploy script 수정
  .github/workflows/deploy-external-api.yml
Labels: enhancement

#158 Api: ✏️ Proxy 서버로 IP Logging 위임을 통한 WAS 애플리케이션 내 인터셉터 제거
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/interceptor/SignEventLogInterceptor.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/GetSpendingsByCategoryControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryUpdateControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/notification/controller/GetNotificationsControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/question/controller/QuestionControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/storage/controller/StorageControllerTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/IpAddressHeaderConverter.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLog.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLogRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLogService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/domain/SignInLog.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/domain/SignInLogId.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/repository/SignInLogRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/service/SignInLogService.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/type/IpAddressHeader.java
Labels: fix
