Repository CollaBu/pennyway-was, pull requests merged in 2024-06, with the labels that each got.

#101 Api: 🐛 태그 생성 & 릴리즈 자동화 파이프라인 후 배포 workflows call
  .github/workflows/create-tag-and-release.yml
  .github/workflows/deploy-batch.yml
  .github/workflows/deploy-external-api.yml
Labels: bug

#102 Api: 🐛 object-key의 depth 수정을 위한 템플릿 수정
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ObjectKeyType.java
Labels: bug

#103 Api: ✏️ 목표 금액 플로우 변경에 따른 API 스펙 변경
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountSaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/TargetAmountManager.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/TargetAmountFixture.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/aop/DistributedLockAop.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redisson/DistributedLock.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redisson/DistributedLockPrefix.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/domain/TargetAmount.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/exception/TargetAmountErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/coupon/TestCouponDecreaseService.java
Labels: fix

#106 Api: ✏️ 문의하기 응답속도 개선을 위한 이벤트 핸들러 비동기 처리
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/MailEventHandling.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MailConfig.java
Labels: fix

#108 Api: 📝 Readme-v0.0.3
  README.md
  pennyway-app-external-api/README.md
Labels: documentation

#105 Api: ✨ 사용자 프로필 이미지 등록 요청 API 구현
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/dto/PresignedUrlDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/service/StorageService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/AwsS3Provider.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ObjectKeyPattern.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/ObjectKeyType.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/common/exception/StorageErrorCode.java
  pennyway-infra/src/main/java/kr/co/pennyway/infra/config/AwsS3Config.java
  pennyway-infra/src/main/resources/application-infra.yml
Labels: enhancement

#109 Api: ✨ 최근 목표 금액 조회 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/RecentTargetAmountSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/target/repository/RecentTargetAmountSearchTest.java
Labels: enhancement

#111 Api: ✏️ 엔티티 생성자 및 수정 메서드 유효성 검사 추가
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/AuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/OAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/UserAuthControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/service/UserGeneralSignServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/DeviceTokenRegisterServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/DeviceTokenUnregisterServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/PasswordUpdateServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/UserFixture.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/DeviceToken.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/question/domain/Question.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/domain/TargetAmount.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/NotifySetting.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepositoryTest.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/target/repository/RecentTargetAmountSearchTest.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserExtendedRepositoryTest.java
  pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserSoftDeleteTest.java
Labels: fix

#110 Api: ✏️ 월별 지출내역 조회시 발생하는 N+1 문제 개선
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingCustomCategoryFixture.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
  pennyway-domain/src/main/resources/application-domain.yml
Labels: fix

#112 🔧 목표 금액 유즈 케이스 리팩토링
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/RecentTargetAmountSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountDeleteService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountSaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
Labels: refactoring

#113 🔧 지출 내역 유즈케이스 리팩토링
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingDeleteService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingUpdateServiceTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
Labels: refactoring

#114 Api: 🔧 지출 카테고리 유즈케이스 리팩토링
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingCategoryMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingCategorySaveService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingCategorySearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java
Labels: refactoring

#115 Api: ✏️ 가장 최근에 설정한 목표 금액 조회 API 응답 시 날짜 데이터 추가
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountSearchService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java
Labels: fix

#116 Api: ✏️ 문의하기 API content 글자 수 제한 및 사용자 이름 정규식 수정
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/dto/QuestionReq.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/question/controller/QuestionControllerTest.java
Labels: fix

#117 Api: 🐛 월별 지출내역 조회 쿼리 버그 수정
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
Labels: bug

#118 Api: ✨ 사용자 프로필 수정 API
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java
  pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/query/VerificationType.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/service/NameUpdateServiceTest.java
  pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateServiceTest.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/phone/PhoneCodeKeyType.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/repository/UserRepository.java
  pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
Labels: enhancement
